name: Fabrica de APK ClasicoFilm

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Descargar el codigo del repositorio
      uses: actions/checkout@v4

    - name: 2. Instalar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: 3. Instalar Java (Necesario para Android)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: 4. Instalar Android SDK
      uses: android-actions/setup-android@v3

    - name: 5. Instalar Apache Cordova
      run: npm install -g cordova

    - name: 6. Crear estructura de Cordova con Plugins de Red Avanzados
      run: |
        cordova create carpeta_temporal com.clasicofilm.tv "ClasicoFilm TV"
        cd carpeta_temporal
        # Instalamos los plugins nativos de red para saltarnos el bloqueo del WebView
        cordova plugin add cordova-plugin-advanced-http
        cordova plugin add cordova-plugin-whitelist || true
        cordova platform add android
        # Reemplazar los archivos por los tuyos del repositorio
        rm -rf www/*
        cp ../index.html www/
        cp ../index.js www/
        cp ../config.xml .
        
    - name: 7. Compilar la APK de Android (Modo Debug)
      run: |
        cd carpeta_temporal
        cordova build android --device

    - name: 8. Guardar la APK generada para descargar
      uses: actions/upload-artifact@v4
      with:
        name: ClasicoFilmTV-APK
        path: carpeta_temporal/platforms/android/app/build/outputs/apk/debug/app-debug.apk
